// GENERATED by src/adapter/opencode/install-plugin.mjs from plugin-entry.mjs —
// do not edit by hand; edit the source.
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "../../src/adapter/engine.mjs";
import { decide, decidePrompt } from "../../src/adapter/opencode/normalise.mjs";

const ADAPTER = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "src", "adapter");

// Resolve whether the calling session is the orchestrator (no parentID, or agent id
// `ai-dev`). FAIL-OPEN to false on any lookup failure — a miss never produces a false
// denial; persona is the fail-safe (matches the engine's fail-open-on-actor contract).
async function isOrchestrator(client, sessionID) {
  try {
    if (!client || !client.session || !client.session.get || !sessionID) return false;
    const res = await client.session.get({ path: { id: sessionID } });
    const data = (res && res.data) || {};
    if (data.agent === "ai-dev") return true;
    return data.parentID == null;
  } catch { return false; }
}

export const AiPmEnforcement = async (ctx) => {
  const root = (ctx && (ctx.directory || ctx.worktree)) || process.cwd();
  const config = loadConfig(ADAPTER);
  return {
    "tool.execute.before": async (input, output) => {
      const isOrch = await isOrchestrator(ctx && ctx.client, input && input.sessionID);
      const r = decide(input && input.tool, (output && output.args) || {}, root, isOrch, config);
      if (r.verdict === "deny") throw new Error("[ai-dev] " + r.reason);
    },
    // chat.message — OpenCode's analog of Claude's UserPromptSubmit: it fires once
    // per user message before the LLM call, and output.parts is MUTABLE. This is
    // how the inject class is REALISED on OpenCode: extract the user text, ask the
    // SHARED engine to decide the prompt-class rules, and on an inject push a text
    // part — one-shot context for THIS turn only. The plugin supplies ONLY the
    // mechanism; the verb list and the predicate stay in deny-rules.json + the
    // engine (single source, invariant 6). No-op for allow; ask is unsupported on
    // OpenCode (falls back to persona) so it is left untouched here.
    "chat.message": async (input, output) => {
      const parts = (output && output.parts) || [];
      const userText = parts
        .filter((p) => p && p.type === "text" && typeof p.text === "string")
        .map((p) => p.text)
        .join("\n");
      const isOrch = await isOrchestrator(ctx && ctx.client, input && input.sessionID);
      const r = decidePrompt(userText, root, isOrch, config);
      if (r.verdict === "inject") output.parts.push({ type: "text", text: r.reason });
    },
  };
};
