// GENERATED by src/adapter/opencode/install-plugin.mjs from plugin-entry.mjs —
// do not edit by hand; edit the source.
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "../../src/adapter/engine.mjs";
import { decide } from "../../src/adapter/opencode/normalise.mjs";

const ADAPTER = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "src", "adapter");

// Resolve whether the calling session is the orchestrator (no parentID, or agent id
// `ai-dev`). FAIL-OPEN to false on any lookup failure — a miss never produces a false
// denial; persona is the fail-safe (matches the engine's fail-open-on-actor contract).
async function isOrchestrator(client, sessionID) {
  try {
    if (!client || !client.session || !client.session.get || !sessionID) return false;
    const res = await client.session.get({ path: { id: sessionID } });
    const data = (res && res.data) || {};
    if (data.agent === "ai-dev") return true;
    return data.parentID == null;
  } catch { return false; }
}

export const AiPmEnforcement = async (ctx) => {
  const root = (ctx && (ctx.directory || ctx.worktree)) || process.cwd();
  // Fail-OPEN on a config-load failure: a malformed deny-rules.json yields a NO-OP hook
  // set (no enforcement) rather than crashing the session. Same rationale as the Claude
  // shim's main() try/catch — the tooling dir is immutable and ships a valid registry, so
  // a broken registry means a broken install, not an attack; a crash that kills the
  // session is worse than a fail-open the Operator would otherwise route around by
  // disabling the plugin. The immutable tooling dir is the compensating control.
  let config;
  try { config = loadConfig(ADAPTER); }
  catch (e) {
    console.error("[ai-dev] config load failed, enforcement off this session: " + (e && e.message ? e.message : String(e)));
    return {};
  }
  return {
    "tool.execute.before": async (input, output) => {
      const isOrch = await isOrchestrator(ctx && ctx.client, input && input.sessionID);
      const r = decide(input && input.tool, (output && output.args) || {}, root, isOrch, config);
      if (r.verdict === "deny") throw new Error("[ai-dev] " + r.reason);
    },
    // No `chat.message` hook: the inject class is persona-fallback on OpenCode (see
    // the file header — the push crashed opencode 1.17.8 and rendered unreliably).
  };
};
