// OpenCode realisation of the adapter's enforce-deny + inject contract point —
// the DEPLOY of the plugin. Generates the file OpenCode actually loads
// (.opencode/plugins/ai-dev.mjs — PLURAL, opencode 1.17) FROM the source entry
// src/adapter/opencode/plugin-entry.mjs.
//
// WHY a generator, not a copy or a thin re-export. opencode 1.17 only registers
// hooks off a plugin function DEFINED INLINE in the loaded module (a bare
// re-export of an imported function loads but its hooks NEVER fire — dogfood
// finding, src/adapter/INSTALL.md). So the deployed file must inline the hook bodies;
// it cannot `export { X } from "../source"`. The deployed file differs from the
// source in TWO ways that both bear on the imported rule-logic path (engine +
// decide/decidePrompt): the ADAPTER LOCATION, and the DEPTH — the deployed
// .opencode/plugins/ai-dev.mjs is 2 levels deep, the source
// src/adapter/opencode/plugin-entry.mjs is 3, so EVERY layout drops one `../`:
//   • downstream: <root>/.ai-dev/tooling/src/adapter  (same target, one fewer `../` for the shallower deploy)
//   • this repo / dev: <root>/src/adapter             (retarget .ai-dev/tooling/src/adapter → src/adapter, also 2 `../`)
// Generating the deployed file mechanically — instead of hand-maintaining a second
// copy — is what keeps the two from drifting (the manifesto's "two copies rot",
// applied to the enforcement layer itself). install-plugin.test.mjs is the guard.
//
// Run from the repo root: node src/adapter/opencode/install-plugin.mjs [outPath] [--root <dir>]
//   outPath defaults to .opencode/plugins/ai-dev.mjs (pass a temp path to dry-run).
//   --root sets the TARGET root whose adapter layout is resolved (the rewrite). It
//   defaults to this script's self-located repo root; the unified installer passes
//   the downstream target so the deployed plugin keeps the tooling-submodule path
//   even though the script itself runs from the vendored copy. Backward-compatible:
//   omit it and the dev/this-repo behaviour is unchanged.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SOURCE = path.join(ROOT, "src", "adapter", "opencode", "plugin-entry.mjs");

// The source's adapter location, as it literally appears in plugin-entry.mjs.
const SOURCE_IMPORT_DIR = "../../../.ai-dev/tooling/src/adapter"; // the two import specifiers' prefix
const SOURCE_RESOLVE_SEGS = '"..", "..", "..", ".ai-dev", "tooling", "src", "adapter"'; // the path.resolve segments

const GENERATED_HEADER =
  "// GENERATED by src/adapter/opencode/install-plugin.mjs from plugin-entry.mjs —\n" +
  "// do not edit by hand; edit the source.\n";

// Resolve which adapter layout the TARGET root uses by checking which dir actually
// exists — the same filesystem-resolution idiom the other installers use to locate
// their inputs. Returns the rewrite that retargets the source's adapter path to the
// deployed location. BOTH layouts need a rewrite, because the deployed plugin is one
// level shallower than the source (.opencode/plugins/ vs src/adapter/opencode/): dev
// retargets to src/adapter and drops a `../`; downstream keeps the .ai-dev/tooling
// target but still drops the one `../` the shallower deploy requires.
//
// `layout` lets a caller (a test) force a layout without touching the filesystem.
//
// Dev detection uses plugin-entry.mjs as the sentinel (it is only present in the
// protocol's own src/adapter/opencode/, not in a downstream's src/ tree), so a
// downstream project that happens to have its own src/adapter/ is not misdetected
// as dev even when both dirs exist (e.g. after a self-install on the source repo).
function resolveRewrite(root, layout) {
  const resolved =
    layout ||
    (fs.existsSync(path.join(root, "src", "adapter", "opencode", "plugin-entry.mjs"))
      ? "dev"
      : fs.existsSync(path.join(root, ".ai-dev", "tooling", "src", "adapter"))
        ? "downstream"
        : null);
  if (resolved === "downstream") {
    // Same .ai-dev/tooling target as the source, but the deployed plugin sits
    // one level shallower (.opencode/plugins/, 2 deep) than the source
    // (src/adapter/opencode/, 3 deep), so drop one `../` / one resolve segment —
    // else the import overshoots the project root by one and the plugin throws
    // on load, silently disabling enforcement on every downstream.
    return (text) =>
      text
        .split(SOURCE_IMPORT_DIR)
        .join("../../.ai-dev/tooling/src/adapter")
        .split(SOURCE_RESOLVE_SEGS)
        .join('"..", "..", ".ai-dev", "tooling", "src", "adapter"');
  }
  if (resolved === "dev") {
    return (text) =>
      text
        .split(SOURCE_IMPORT_DIR)
        .join("../../src/adapter")
        .split(SOURCE_RESOLVE_SEGS)
        .join('"..", "..", "src", "adapter"');
  }
  throw new Error(
    `install-plugin: no adapter dir found under ${root} (looked for .ai-dev/tooling/src/adapter and src/adapter)`,
  );
}

// Generate the deployed plugin text from the source entry. The source's leading
// inline-requirement comment block is DROPPED (its WHY now lives here, the single
// home) and replaced by the short generated-file header; the hook bodies are
// carried through verbatim, only the adapter path retargeted.
export function generate(root = ROOT, layout) {
  const src = fs.readFileSync(SOURCE, "utf8");
  // Strip the source's leading comment block — every run of `//` lines + blank
  // lines up to the first import — so the output leads with the generated header.
  const body = src.replace(/^(?:\/\/[^\n]*\n|\s*\n)*/, "");
  const rewrite = resolveRewrite(root, layout);
  const retargeted = rewrite ? rewrite(body) : body;
  return GENERATED_HEADER + retargeted;
}

// Write the generated plugin to outPath, then SELF-VERIFY it actually loads from
// its installed location. Returns the path written so a test can read the result
// without re-deriving it.
//
// WHY the self-verify (D7 class-prevention for a 3-time recurring silent fail-open):
// a plugin can deploy yet throw on load — a wrong `../` depth, an un-vendored
// adapter, a stale cached layout — and OpenCode then registers NO hooks, leaving the
// whole [mechanical] boundary floor silently OFF while the install prints success.
// A real `import()` of the just-written file exercises its top-level imports against
// the actual installed layout (the same resolution the live OpenCode loader does), so
// it fails iff the deployed plugin cannot load. async because import() is a promise.
//
// Honesty scope: this proves the plugin LOADS (the path / ES-module-resolution class);
// it does NOT prove OpenCode invokes the hook at runtime (the registration class —
// covered by the opencode.json `plugin`-key wiring + install.test.mjs). Load check,
// not a registration check.
export async function install(outPath, root = ROOT, layout) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  const out = generate(root, layout);
  fs.writeFileSync(outPath, out);
  console.log(`wrote ${path.relative(root, outPath)}  (generated from plugin-entry.mjs)`);
  try {
    await import(pathToFileURL(outPath).href);
  } catch (e) {
    const detail = e && e.message ? e.message : String(e);
    throw new Error(
      `install-plugin: the deployed plugin at ${outPath} does not load — ` +
        `enforcement would be silently off. Underlying load error: ${detail}`,
      { cause: e },
    );
  }
  return outPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const rootIdx = args.indexOf("--root");
  const root = rootIdx >= 0 ? path.resolve(args[rootIdx + 1]) : ROOT;
  const outArg = args.find((a, i) => !a.startsWith("--") && (rootIdx < 0 || i !== rootIdx + 1));
  const outPath = outArg ? path.resolve(outArg) : path.join(root, ".opencode", "plugins", "ai-dev.mjs");
  // A self-verify load failure rejects this promise; surface it as a non-zero exit
  // (the unified installer spawns this CLI as a child — its non-zero exit propagates
  // up through execFileSync and aborts the install with no success summary).
  await install(outPath, root);
}
