// OpenCode realisation of the adapter's enforce-deny + inject contract point —
// the DEPLOY of the plugin. Generates the file OpenCode actually loads
// (.opencode/plugins/ai-dev.mjs — PLURAL, opencode 1.17) FROM the source entry
// src/adapter/opencode/plugin-entry.mjs.
//
// WHY a generator, not a copy or a thin re-export. opencode 1.17 only registers
// hooks off a plugin function DEFINED INLINE in the loaded module (a bare
// re-export of an imported function loads but its hooks NEVER fire — dogfood
// finding, src/adapter/INSTALL.md). So the deployed file must inline the hook bodies;
// it cannot `export { X } from "../source"`. The ONE thing that differs between
// source and deployed is the ADAPTER LOCATION — the rule logic (engine +
// decide/decidePrompt) is imported, and its path depends on where the adapter is
// vendored in the target environment:
//   • downstream: <root>/.ai-dev/tooling/src/adapter  (the source's own path → no rewrite)
//   • this repo / dev: <root>/src/adapter             (rewrite .ai-dev/tooling/src/adapter → src/adapter)
// Generating the deployed file mechanically — instead of hand-maintaining a second
// copy — is what keeps the two from drifting (the manifesto's "two copies rot",
// applied to the enforcement layer itself). install-plugin.test.mjs is the guard.
//
// Run from the repo root: node src/adapter/opencode/install-plugin.mjs [outPath] [--root <dir>]
//   outPath defaults to .opencode/plugins/ai-dev.mjs (pass a temp path to dry-run).
//   --root sets the TARGET root whose adapter layout is resolved (the rewrite). It
//   defaults to this script's self-located repo root; the unified installer passes
//   the downstream target so the deployed plugin keeps the tooling-submodule path
//   even though the script itself runs from the vendored copy. Backward-compatible:
//   omit it and the dev/this-repo behaviour is unchanged.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SOURCE = path.join(ROOT, "src", "adapter", "opencode", "plugin-entry.mjs");

// The source's adapter location, as it literally appears in plugin-entry.mjs.
const SOURCE_IMPORT_DIR = "../../../.ai-dev/tooling/src/adapter"; // the two import specifiers' prefix
const SOURCE_RESOLVE_SEGS = '"..", "..", "..", ".ai-dev", "tooling", "src", "adapter"'; // the path.resolve segments

const GENERATED_HEADER =
  "// GENERATED by src/adapter/opencode/install-plugin.mjs from plugin-entry.mjs —\n" +
  "// do not edit by hand; edit the source.\n";

// Resolve which adapter layout the TARGET root uses by checking which dir actually
// exists — the same filesystem-resolution idiom the other installers use to locate
// their inputs. Returns the rewrite that retargets the source's adapter path to the
// target, or null when the source path is already correct (downstream layout).
//
// `layout` lets a caller (a test) force a layout without touching the filesystem.
function resolveRewrite(root, layout) {
  const resolved =
    layout ||
    (fs.existsSync(path.join(root, ".ai-dev", "tooling", "src", "adapter"))
      ? "downstream"
      : fs.existsSync(path.join(root, "src", "adapter"))
        ? "dev"
        : null);
  if (resolved === "downstream") return null; // source path already correct
  if (resolved === "dev") {
    return (text) =>
      text
        .split(SOURCE_IMPORT_DIR)
        .join("../../src/adapter")
        .split(SOURCE_RESOLVE_SEGS)
        .join('"..", "..", "src", "adapter"');
  }
  throw new Error(
    `install-plugin: no adapter dir found under ${root} (looked for .ai-dev/tooling/src/adapter and src/adapter)`,
  );
}

// Generate the deployed plugin text from the source entry. The source's leading
// inline-requirement comment block is DROPPED (its WHY now lives here, the single
// home) and replaced by the short generated-file header; the hook bodies are
// carried through verbatim, only the adapter path retargeted.
export function generate(root = ROOT, layout) {
  const src = fs.readFileSync(SOURCE, "utf8");
  // Strip the source's leading comment block — every run of `//` lines + blank
  // lines up to the first import — so the output leads with the generated header.
  const body = src.replace(/^(?:\/\/[^\n]*\n|\s*\n)*/, "");
  const rewrite = resolveRewrite(root, layout);
  const retargeted = rewrite ? rewrite(body) : body;
  return GENERATED_HEADER + retargeted;
}

// Write the generated plugin to outPath. Returns the path written so a test can
// read the result without re-deriving it.
export function install(outPath, root = ROOT, layout) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  const out = generate(root, layout);
  fs.writeFileSync(outPath, out);
  console.log(`wrote ${path.relative(root, outPath)}  (generated from plugin-entry.mjs)`);
  return outPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const rootIdx = args.indexOf("--root");
  const root = rootIdx >= 0 ? path.resolve(args[rootIdx + 1]) : ROOT;
  const outArg = args.find((a, i) => !a.startsWith("--") && (rootIdx < 0 || i !== rootIdx + 1));
  const outPath = outArg ? path.resolve(outArg) : path.join(root, ".opencode", "plugins", "ai-dev.mjs");
  install(outPath, root);
}
